apiVersion: apps/v1
kind: Deployment
metadata:
  name: droneops-sim
  namespace: default
  labels:
    app: droneops-sim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: droneops-sim
  template:
    metadata:
      labels:
        app: droneops-sim
    spec:
      containers:
      - name: droneops-sim
        image: registry.local/droneops-sim:latest
        imagePullPolicy: IfNotPresent
        args: ["--config", "/etc/droneops-sim/config/fleet.yaml", "--schema", "/etc/droneops-sim/schema/fleet.cue"]
        env:
        - name: GREPTIMEDB_ENDPOINT
          value: "127.0.0.1:4001"   # override for real deployments
        - name: GREPTIMEDB_TABLE
          value: "drone_telemetry"
        - name: CLUSTER_ID
          value: "mission-01"
        volumeMounts:
        - name: config
          mountPath: /etc/droneops-sim/config
        - name: schema
          mountPath: /etc/droneops-sim/schema
        ports:
        - name: metrics
          containerPort: 8080 # reserved for future metrics endpoint
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          exec:
            command: ["/bin/sh", "-c", "echo ready"]
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command: ["/bin/sh", "-c", "echo alive"]
          initialDelaySeconds: 10
          periodSeconds: 20
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          readOnlyRootFilesystem: true
      volumes:
      - name: config
        configMap:
          name: droneops-sim-config
      - name: schema
        configMap:
          name: droneops-sim-schema
      securityContext:
        fsGroup: 65532
---
apiVersion: v1
kind: Service
metadata:
  name: droneops-sim
  namespace: default
  labels:
    app: droneops-sim
spec:
  selector:
    app: droneops-sim
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: droneops-sim
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: droneops-sim
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: droneops-sim-config
data:
  fleet.yaml: |
    regions:
      - name: central-europe
        center_lat: 48.2
        center_lon: 16.4
        radius_km: 300
    fleets:
      - name: recon-swarm
        model: small-fpv
        count: 20
        movement_pattern: patrol
        home_region: central-europe
        behavior:
          battery_drain_rate: 0.5
          failure_rate: 0.02
          speed_min_kmh: 50
          speed_max_kmh: 90
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: droneops-sim-schema
data:
  fleet.cue: |
    package schemas

    regions: [...{
        name:       string & !=""
        center_lat: number
        center_lon: number
        radius_km:  number
    }]
    fleets: [...{
        name:             string & !=""
        model:            string & !=""
        count:            int & >0
        movement_pattern: string & !=""
        home_region:      string & !=""
        behavior: {
            battery_drain_rate: number
            failure_rate:       number
            speed_min_kmh:      number
            speed_max_kmh:      number
        }
    }]
