apiVersion: batch/v1
kind: CronJob
metadata:
  name: sling-sync
  namespace: default
spec:
  schedule: "*/5 * * * *"  # run every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sling
            image: slingdata/sling-cli:latest
            args: ["sync", "--config", "/etc/sling/mission-to-command-sling.yaml"]
            env:
            - name: MISSION_CLUSTER_ID
              value: "mission-01"
            - name: ENEMY_DETECTION_TABLE
              value: "enemy_detection"
            - name: SWARM_EVENT_TABLE
              value: "swarm_events"
            - name: SIMULATION_STATE_TABLE
              value: "simulation_state"
            - name: SYNC_JOB_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            volumeMounts:
            - name: sling-config
              mountPath: /etc/sling
          restartPolicy: OnFailure
          volumes:
          - name: sling-config
            configMap:
              name: sling-pipeline
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sling-pipeline
data:
  mission-to-command-sling.yaml: |
    source:
      type: postgres
      connection: "postgres://user:pass@mission-db:5432/dbname"
      table: drone_telemetry
      incremental_column: ts

      target:
        type: postgres
        connection: "postgres://user:pass@command-db:5432/dbname"
      table: drone_telemetry

    transforms:
      - add_column:
          name: synced_from
          value: "{{ env.MISSION_CLUSTER_ID }}"
      - add_column:
          name: synced_at
          value: "{{ now() }}"
      - add_column:
          name: synced_id
          value: "{{ env.SYNC_JOB_ID }}"

    options:
      on_conflict: skip

  enemy-detection-sling.yaml: |
    source:
      type: postgres
      connection: "postgres://user:pass@mission-db:5432/dbname"
      table: enemy_detection
      incremental_column: ts

    target:
      type: postgres
      connection: "postgres://user:pass@command-db:5432/dbname"
      table: enemy_detection

    options:
      on_conflict: skip

  swarm-events-sling.yaml: |
    source:
      type: postgres
      connection: "postgres://user:pass@mission-db:5432/dbname"
      table: swarm_events
      incremental_column: ts

    target:
      type: postgres
      connection: "postgres://user:pass@command-db:5432/dbname"
      table: swarm_events

    options:
      on_conflict: skip

  simulation-state-sling.yaml: |
    source:
      type: postgres
      connection: "postgres://user:pass@mission-db:5432/dbname"
      table: simulation_state
      incremental_column: ts

    target:
      type: postgres
      connection: "postgres://user:pass@command-db:5432/dbname"
      table: simulation_state

    options:
      on_conflict: skip
