replicaCount: 1

image:
  repository: registry.local/droneops-sim
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  adminWebUIPort: 8080

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

config:
  simulation:
    zones:
      - name: central-europe
        center_lat: 48.2
        center_lon: 16.4
        radius_km: 300
    missions:
      - name: surveillance-alpha
        zone: central-europe
        description: Recon and patrol of key areas
      - name: cargo-beta
        zone: central-europe
        description: Deliver supplies between bases
    fleets:
      - name: recon-swarm
        model: small-fpv
        count: 20
        movement_pattern: patrol
        home_region: central-europe
        behavior:
          battery_drain_rate: 0.5
          failure_rate: 0.02
          speed_min_kmh: 50
          speed_max_kmh: 90
          sensor_error_rate: 0.01
          dropout_rate: 0.01
          battery_anomaly_rate: 0.01
      - name: transport-squad
        model: medium-uav
        count: 5
        movement_pattern: point-to-point
        home_region: central-europe
        behavior:
          battery_drain_rate: 0.3
          failure_rate: 0.01
          speed_min_kmh: 80
          speed_max_kmh: 140
          sensor_error_rate: 0.01
          dropout_rate: 0.01
          battery_anomaly_rate: 0.01
      - name: heavy-support
        model: large-uav
        count: 2
        movement_pattern: loiter
        home_region: central-europe
        behavior:
          battery_drain_rate: 0.2
          failure_rate: 0.005
          speed_min_kmh: 100
          speed_max_kmh: 180
          sensor_error_rate: 0.01
          dropout_rate: 0.01
          battery_anomaly_rate: 0.01

schema:
  simulation:
    package: schemas
    zones:
      - name: string & !=""
        center_lat: number
        center_lon: number
        radius_km: number
    missions:
      - name: string & !=""
        zone: string
        description: string
    fleets:
      - name: string & !=""
        model: string & !=""
        count: int & >0
        movement_pattern: string & !=""
        home_region: string & !=""
        behavior:
          battery_drain_rate: number
          failure_rate: number
          speed_min_kmh: number
          speed_max_kmh: number
          sensor_error_rate: number
          dropout_rate: number
          battery_anomaly_rate: number
