apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  fleet.yaml: |
    {{- toYaml .Values.config.fleet | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-schema
data:
  fleet.cue: |
    {{- toYaml .Values.schema.fleet | nindent 4 }}
