apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  simulation.yaml: |
    {{- toYaml .Values.config.simulation | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-schema
data:
  simulation.cue: |
    {{- toYaml .Values.schema.simulation | nindent 4 }}
